// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMediaServerPort() {
  return window['go']['main']['App']['GetMediaServerPort']();
}

export function HasFFmpeg() {
  return window['go']['main']['App']['HasFFmpeg']();
}

export function OpenVideo(arg1) {
  return window['go']['main']['App']['OpenVideo'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveVideo(arg1, arg2) {
  return window['go']['main']['App']['SaveVideo'](arg1, arg2);
}
