// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMediaServerPort():Promise<number>;

export function HasFFmpeg():Promise<boolean>;

export function OpenVideo(arg1:string):Promise<Record<string, string>>;

export function Quit():Promise<void>;

export function SaveVideo(arg1:string,arg2:Array<main.Keyframe>):Promise<void>;
